/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package spotlight;

/**
 *
 * @author Ugur
 */
public class adminpanel extends javax.swing.JFrame {

    /**
     * Creates new form adminpanel
     */
     private platformlogin giris;
    public adminpanel (platformlogin gir) {
        this.giris=gir;
        initComponents();
    }

    private adminpanel() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logout = new javax.swing.JButton();
        background = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        manageusers = new javax.swing.JMenu();
        viewallusers = new javax.swing.JMenuItem();
        deleteusers = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        platformnews = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1366, 768));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });
        getContentPane().setLayout(null);

        logout.setBackground(new java.awt.Color(0, 153, 255));
        logout.setForeground(new java.awt.Color(255, 255, 255));
        logout.setText("LOGOUT");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        getContentPane().add(logout);
        logout.setBounds(1200, 50, 120, 30);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/spotlight/backadmin.jpg"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, 0, 690, 380);

        manageusers.setText("Manage Users");
        manageusers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageusersActionPerformed(evt);
            }
        });

        viewallusers.setText("View all Users");
        viewallusers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewallusersActionPerformed(evt);
            }
        });
        manageusers.add(viewallusers);

        deleteusers.setText("Delete Users");
        deleteusers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteusersActionPerformed(evt);
            }
        });
        manageusers.add(deleteusers);

        jMenuBar1.add(manageusers);

        jMenu3.setText("Manage News");

        platformnews.setText("Platform News");
        platformnews.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                platformnewsActionPerformed(evt);
            }
        });
        jMenu3.add(platformnews);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewallusersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewallusersActionPerformed
        new viewuser(this).setVisible(true);
    }//GEN-LAST:event_viewallusersActionPerformed

    private void deleteusersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteusersActionPerformed
        new deleteuser(this).setVisible(true);
    }//GEN-LAST:event_deleteusersActionPerformed

    private void manageusersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageusersActionPerformed

    }//GEN-LAST:event_manageusersActionPerformed

    private void platformnewsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_platformnewsActionPerformed
        new platformnews(this).setVisible(true);
    }//GEN-LAST:event_platformnewsActionPerformed

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        background.setSize(this.getSize());
    }//GEN-LAST:event_formComponentResized

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        dispose();
        new platformlogin().setVisible(true);
    }//GEN-LAST:event_logoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminpanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminpanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminpanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminpanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminpanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JMenuItem deleteusers;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JButton logout;
    private javax.swing.JMenu manageusers;
    private javax.swing.JMenuItem platformnews;
    private javax.swing.JMenuItem viewallusers;
    // End of variables declaration//GEN-END:variables
}
