/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package spotlight;

import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author Ugur
 */
public class myposts extends javax.swing.JFrame {

    /**
     * Creates new form myposts
     */
    
    private timeline postg;
    public myposts(timeline postg) {
        initComponents();
    }
     public myposts(String gelen) {
        initComponents();
         id.setText(gelen);
         id.setVisible(false);
         populateMyTable();
    }
public Connection getConnection(){
        Connection con = null;
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/spotlight?useUnicode=true&characterEncoding=UTF-8", "ugur","1905");
        } catch (SQLException ex) {
            Logger.getLogger(timeline.class.getName()).log(Level.SEVERE, null, ex);
        }
        return con;
    }
     
      public void populateMyTable(){
          try{
        ArrayList<ForCategories> listem = MyTable();
        String[] columnName = {"postid","postpic","posttag","category"};
        
        Object[][] rows = new Object[listem.size()][4];
        for(int i = 0; i < listem.size(); i++){
    
            
            
            rows[i][0] = listem.get(i).getpostID();
            if(listem.get(i).getMyImage() != null){
                
             ImageIcon image = new ImageIcon(new ImageIcon(listem.get(i).getMyImage()).getImage()
             .getScaledInstance(150, 120, Image.SCALE_SMOOTH) );   
                
            rows[i][1] = image;
            }
            else{ 
                rows[i][1] = null;
            }
          
            rows[i][2] = listem.get(i).getPostTag();
              rows[i][3] = listem.get(i).getCategory();
            
            
        }
        
        PostModel model = new PostModel(rows, columnName);
        
        categoriestable.setModel(model);
        categoriestable.setRowHeight(120);
        categoriestable.getColumnModel().getColumn(1).setPreferredWidth(150);
    }catch(ArrayIndexOutOfBoundsException ex) {
       
        
            }
      }
       public ArrayList<ForCategories> MyTable(){
   ArrayList<ForCategories> mylist = new ArrayList<ForCategories>();
   Connection con=getConnection();
   Statement st;
   ResultSet rs;
   String myid=id.getText();
   
   
   try {
       
   st = con.createStatement();
   rs = st.executeQuery("SELECT `postpic`, `postid`, `userid`, `posttag`, `category`  FROM `posts` WHERE `userid`= '"+myid+"'");
   
   ForCategories da;
   while(rs.next()){
   da = new ForCategories(
   rs.getBytes("postpic"),
   rs.getInt("postid"),
   rs.getString("userid"),
   rs.getString("posttag"),
   rs.getString("category")
  
   );
   mylist.add(da);
   
   }
   
   } catch (SQLException ex) {
   Logger.getLogger(timeline.class.getName()).log(Level.SEVERE, null, ex);
   }
   return mylist;
   }
    private myposts() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        id = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        categoriespane = new javax.swing.JScrollPane();
        categoriestable = new javax.swing.JTable();
        back = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(null);
        getContentPane().add(id);
        id.setBounds(10, 24, 114, 48);

        jPanel1.setOpaque(false);

        categoriestable.setAutoCreateRowSorter(true);
        categoriestable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
            }
        ));
        categoriestable.setMaximumSize(new java.awt.Dimension(2312320, 22320));
        categoriestable.setMinimumSize(new java.awt.Dimension(1366, 768));
        categoriestable.setPreferredSize(new java.awt.Dimension(5000, 2500));
        categoriestable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                categoriestableMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                categoriestableMousePressed(evt);
            }
        });
        categoriespane.setViewportView(categoriestable);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 469, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(categoriespane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 402, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(categoriespane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(570, 150, 469, 402);

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/spotlight/4.jpg"))); // NOI18N
        back.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                backComponentResized(evt);
            }
        });
        getContentPane().add(back);
        back.setBounds(0, 0, 1366, 520);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void categoriestableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_categoriestableMouseClicked
        boolean b=categoriestable.isEditing();
        if(b==false){

            JOptionPane.showMessageDialog(null,"You can't edit the post.");

        }
    }//GEN-LAST:event_categoriestableMouseClicked

    private void categoriestableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_categoriestableMousePressed
       
    }//GEN-LAST:event_categoriestableMousePressed

    private void backComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_backComponentResized
back.setSize(this.getSize());        // TODO add your handling code here:
    }//GEN-LAST:event_backComponentResized

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(myposts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(myposts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(myposts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(myposts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new myposts().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JScrollPane categoriespane;
    private javax.swing.JTable categoriestable;
    private javax.swing.JLabel id;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
