package spotlight;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ugur
 */
public class platformlogin extends javax.swing.JFrame {

    /**
     * Creates new form platformlogin
     */
    public platformlogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        entryid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        entrypass = new javax.swing.JPasswordField();
        logbutton = new javax.swing.JButton();
        regbutton = new javax.swing.JButton();
        logwarn = new javax.swing.JLabel();
        logadmin = new javax.swing.JButton();
        back = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1366, 768));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setForeground(new java.awt.Color(255, 204, 204));
        jPanel1.setToolTipText("");
        jPanel1.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("LOGIN");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("Username");

        entryid.setBackground(new java.awt.Color(240, 240, 240));
        entryid.setForeground(new java.awt.Color(153, 51, 0));
        entryid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entryidActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("Password");

        entrypass.setForeground(new java.awt.Color(153, 51, 0));

        logbutton.setBackground(new java.awt.Color(0, 102, 102));
        logbutton.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        logbutton.setForeground(new java.awt.Color(255, 255, 255));
        logbutton.setText("Login");
        logbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logbuttonActionPerformed(evt);
            }
        });

        regbutton.setBackground(new java.awt.Color(255, 255, 255));
        regbutton.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        regbutton.setForeground(new java.awt.Color(0, 102, 102));
        regbutton.setText("Register");
        regbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regbuttonActionPerformed(evt);
            }
        });

        logwarn.setForeground(new java.awt.Color(255, 0, 51));

        logadmin.setBackground(new java.awt.Color(0, 102, 102));
        logadmin.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        logadmin.setForeground(new java.awt.Color(255, 255, 255));
        logadmin.setText("Admin");
        logadmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logadminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(logadmin, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(logbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(entrypass, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(regbutton))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(entryid, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(logwarn, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(entryid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(entrypass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(logwarn, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(logadmin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(regbutton)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(570, 150, 352, 365);

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/spotlight/5.jpg"))); // NOI18N
        getContentPane().add(back);
        back.setBounds(0, 0, 360, 440);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void entryidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entryidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entryidActionPerformed

    private void logbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logbuttonActionPerformed
        String eid = entryid.getText();				
        String epass = entrypass.getText();		
      
        Connection con;
        PreparedStatement ps;

        try
        {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/spotlight?useUnicode=true&characterEncoding=UTF-8", "ugur", "1905");

            
            ps = con.prepareStatement("SELECT `userid`, `userpass` FROM  `users` WHERE `userid` = ? AND `userpass` = ?");
            ps.setString(1, eid);
            ps.setString(2, epass);

            ResultSet result = ps.executeQuery();

            if(result.next()){			

                JOptionPane.showMessageDialog(null, "You are redirected to timeline, please wait...");			

                logwarn.setVisible(false);

                new timeline (this).setVisible(false);			
                new timeline(eid).setVisible(true);

                dispose();										

           
            }else {
                JOptionPane.showMessageDialog(null, "Something is wrong.");
                logwarn.setText("Password or ID is wrong, please try again.");
                logwarn.setVisible(true);
           

                if ("".equals(epass) && "".equals(eid)) {			
                    logwarn.setText("Please, enter the ID and the password!");
                    entryid.requestFocusInWindow();								

                } else if ("".equals(eid)) {							
                    logwarn.setText("Please, enter the ID!");
                    entryid.requestFocusInWindow();					

                } else if ("".equals(epass)) {					
                    logwarn.setText("Please, enter the password!");
                    entrypass.requestFocusInWindow();							

                } }
            } catch (SQLException ex) {
                Logger.getLogger(platformlogin.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_logbuttonActionPerformed

    private void regbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regbuttonActionPerformed
        new signup().setVisible(true);
        dispose();
    }//GEN-LAST:event_regbuttonActionPerformed

    private void logadminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logadminActionPerformed
    String aid = entryid.getText();				
        String apass = entrypass.getText();				
        //IF TEXTAREAS ARE NULL
        Connection connect;
        PreparedStatement pse;

        try
        {
            connect = DriverManager.getConnection("jdbc:mysql://localhost:3306/spotlight?useUnicode=true&characterEncoding=UTF-8", "ugur", "1905");

           
            pse = connect.prepareStatement("SELECT `adminid`, `adminpass` FROM  `admin` WHERE `adminid` = ? AND `adminpass` = ?");
            pse.setString(1,aid);
            pse.setString(2, apass);

            ResultSet resultt = pse.executeQuery();

            if(resultt.next()){			

                JOptionPane.showMessageDialog(null, "You are redirected to admin page, please wait...");		
                new adminpanel(this).setVisible(true);
                logwarn.setVisible(false);
                dispose();

                //SHUT THE LOGIN PAGE
            } else {
                JOptionPane.showMessageDialog(null, "Something is wrong.");				
                logwarn.setText("Password or ID is wrong, please try again.");
                logwarn.setVisible(true);						

                if ("".equals(apass) && "".equals(aid)) {			
                    logwarn.setText("Please, enter the ID and the password!");
                    entryid.requestFocusInWindow();									

                } else if ("".equals(aid)) {								
                    logwarn.setText("Please, enter the ID!");
                    entryid.requestFocusInWindow();										

                } else if ("".equals(apass)) {						
                    logwarn.setText("Please, enter the password!");
                    entrypass.requestFocusInWindow();							

                }}}catch (SQLException ex) {
                    Logger.getLogger(platformlogin.class.getName()).log(Level.SEVERE, null, ex);
                }
    }//GEN-LAST:event_logadminActionPerformed

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
back.setSize(this.getSize());         // TODO add your handling code here:
    }//GEN-LAST:event_formComponentResized

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(platformlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(platformlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(platformlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(platformlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new platformlogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JTextField entryid;
    private javax.swing.JPasswordField entrypass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton logadmin;
    private javax.swing.JButton logbutton;
    private javax.swing.JLabel logwarn;
    private javax.swing.JButton regbutton;
    // End of variables declaration//GEN-END:variables
}
