/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package spotlight;

import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Ugur
 */
public class updateprofile extends javax.swing.JFrame {

    /**
     * Creates new form updateprofile
     */
    String ptt;
    private timeline al;
    public updateprofile(timeline all) {
        this.al=all;
        initComponents();
    }
     public updateprofile(String getmyID) {
        initComponents();
        myid.setText(getmyID);
        myid.setVisible(false);
    }
 public ImageIcon ResizeImage(String imgPath){			
        ImageIcon MyImagee = new ImageIcon(imgPath);		
        Image imgg = MyImagee.getImage();					
        Image newwImage = imgg.getScaledInstance(picture.getWidth(), picture.getHeight(),Image.SCALE_SMOOTH);		
        ImageIcon imagee = new ImageIcon(newwImage);		
        return imagee;
    }
    private updateprofile() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        mail = new javax.swing.JTextField();
        nick = new javax.swing.JTextField();
        age = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        pass = new javax.swing.JTextField();
        sex = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        picture = new javax.swing.JLabel();
        myid = new javax.swing.JLabel();
        updatepic = new javax.swing.JButton();
        updatebutton = new javax.swing.JButton();
        back = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1366, 768));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setOpaque(false);
        jPanel1.setLayout(null);

        jLabel6.setForeground(new java.awt.Color(0, 102, 102));
        jLabel6.setText("Sex:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(340, 200, 50, 14);

        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("E-mail:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(340, 310, 50, 10);

        jLabel7.setForeground(new java.awt.Color(0, 102, 102));
        jLabel7.setText("Password:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(330, 240, 70, 14);
        jPanel1.add(mail);
        mail.setBounds(410, 300, 232, 20);

        nick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nickActionPerformed(evt);
            }
        });
        jPanel1.add(nick);
        nick.setBounds(410, 160, 230, 20);
        jPanel1.add(age);
        age.setBounds(410, 270, 232, 20);

        jLabel12.setForeground(new java.awt.Color(0, 102, 102));
        jLabel12.setText("Age:");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(340, 270, 40, 20);
        jPanel1.add(pass);
        pass.setBounds(410, 240, 230, 20);

        sex.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        sex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sexActionPerformed(evt);
            }
        });
        jPanel1.add(sex);
        sex.setBounds(410, 200, 230, 20);

        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("Nickname:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(330, 160, 70, 14);
        jPanel1.add(picture);
        picture.setBounds(413, 11, 230, 123);
        jPanel1.add(myid);
        myid.setBounds(142, 384, 78, 32);

        updatepic.setForeground(new java.awt.Color(0, 102, 102));
        updatepic.setText("Choose a Picture");
        updatepic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatepicActionPerformed(evt);
            }
        });
        jPanel1.add(updatepic);
        updatepic.setBounds(249, 84, 113, 23);

        updatebutton.setForeground(new java.awt.Color(0, 102, 102));
        updatebutton.setText("UPDATE");
        updatebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebuttonActionPerformed(evt);
            }
        });
        jPanel1.add(updatebutton);
        updatebutton.setBounds(528, 369, 120, 23);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(170, 40, 790, 430);

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/spotlight/11.jpg"))); // NOI18N
        getContentPane().add(back);
        back.setBounds(0, 0, 1080, 470);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nickActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nickActionPerformed

    private void sexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sexActionPerformed

    private void updatepicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatepicActionPerformed
        javax.swing.JFileChooser fileChooser = new javax.swing.JFileChooser();          
        fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));   
        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.IMAGE", "jpg","gif","png","jpeg");      
        fileChooser.addChoosableFileFilter(filter);          
        int result = fileChooser.showSaveDialog(null);        
        if(result == javax.swing.JFileChooser.APPROVE_OPTION){             
            File selectedFile = fileChooser.getSelectedFile();       
            String path = selectedFile.getAbsolutePath();          	
            picture.setIcon(ResizeImage(path));                     	
            ptt=path;
            if(path==null){
                JOptionPane.showMessageDialog(null, "Please choose a photo");
            }else{
                JOptionPane.showMessageDialog(null, "Photo is added");
            }
        }
        else if(result == javax.swing.JFileChooser.CANCEL_OPTION){					
            JOptionPane.showMessageDialog(null, "No data");
        }
    }//GEN-LAST:event_updatepicActionPerformed

    private void updatebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebuttonActionPerformed
      String usidd=myid.getText();
  String nicknamee=nick.getText();
        String sexx=(String)sex.getSelectedItem();
        String mypass = pass.getText();
        String mymail = mail.getText();
        String myage = age.getText();
        try {
            InputStream is = new FileInputStream(new File(ptt));
            //GET COONECTION
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/spotlight?useUnicode=true&characterEncoding=UTF-8", "ugur", "1905");
            //STATEMENT
            String sql = "UPDATE users SET userphoto='" + is + "',nickname='" + nicknamee + "', userpass='" + mypass + "', email='" + mymail+ "', age='" + myage + "', sex='" + sexx + "'  WHERE userid='" + usidd + "'";
            Statement s = con.prepareStatement(sql);
            //EXECUTE
            s.execute(sql); 
            JOptionPane.showMessageDialog(null,"The personal information is updated.");

        } catch (SQLException ex) {
            Logger.getLogger(updateprofile.class.getName()).log(Level.SEVERE, null, ex);

        } catch (FileNotFoundException ex) {
            Logger.getLogger(updateprofile.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_updatebuttonActionPerformed

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
back.setSize(this.getSize());        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentResized

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(updateprofile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(updateprofile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(updateprofile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(updateprofile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new updateprofile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField age;
    private javax.swing.JLabel back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField mail;
    private javax.swing.JLabel myid;
    private javax.swing.JTextField nick;
    private javax.swing.JTextField pass;
    private javax.swing.JLabel picture;
    private javax.swing.JComboBox<String> sex;
    private javax.swing.JButton updatebutton;
    private javax.swing.JButton updatepic;
    // End of variables declaration//GEN-END:variables
}
